import '../styles/scss/styles.scss';
import './burger.js';
import './map.js';
import './counter.js';
import './search.js';
import './favorite.js';
import './auth-modal.js';
import './cards.js';
import './renderCards.js';